name: Build PDF Merger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller tkinterdnd2

      # Build the .exe using PyInstaller
      - name: Build the .exe
        run: |
          # Check if tkinterdnd2 is installed properly
          pip show tkinterdnd2
          pyinstaller --onefile --add-data "C:/hostedtoolcache/windows/Python/3.13.1/x64/Lib/site-packages/tkinterdnd2/tkdnd;tkinterdnd2/tkdnd" merger.py

      # Upload the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-merger-exe
          path: dist/merger.exe
